// apps/api/src/harness/loop/simplify-schema.ts
//
// Down-converts a JSON Schema into the subset that restrictive constrained-decoding
// backends (notably Workers AI's tool-grammar engine) can compile. The teacher's
// Phase-2 artifact schema is generated by zod-to-json-schema and contains constructs
// that 500 on Workers AI (verified live: AiError 3043/3044):
//   - `anyOf`/`oneOf` whose branches are OBJECTS (a discriminated union) — the model
//     serving stack cannot build a grammar for a union of object types, even flattened.
//   - tuple-form `items` (an array of per-position schemas).
//   - `const`.
// These are rewritten losslessly enough that the strict Zod validator (which runs on
// the model's output, with a repair loop) still accepts a well-formed response:
//   - object-union  -> a single object: union of properties, intersection of required,
//                      discriminator `enum`s merged, nullable if any branch was null.
//   - tuple items   -> the first item schema (all positions share a type in practice).
//   - const: X      -> enum: [X].
// Scalar unions (e.g. anyOf:[{string}, {null}]) are LEFT INTACT — those compile fine
// on Workers AI, so we must not mangle them.

type Schema = Record<string, unknown>;

function isSchema(v: unknown): v is Schema {
	return typeof v === "object" && v !== null && !Array.isArray(v);
}

function isObjectBranch(s: unknown): s is Schema {
	return isSchema(s) && (s.type === "object" || "properties" in s);
}

function isNullBranch(s: unknown): boolean {
	return isSchema(s) && s.type === "null";
}

// Collect object branches (flattening one level of nested anyOf/oneOf) and whether a
// null branch is present anywhere in the union.
function collectUnion(branches: unknown[]): {
	objects: Schema[];
	hasNull: boolean;
} {
	const objects: Schema[] = [];
	let hasNull = false;
	for (const b of branches) {
		if (isNullBranch(b)) {
			hasNull = true;
		} else if (isObjectBranch(b)) {
			objects.push(b);
		} else if (
			isSchema(b) &&
			(Array.isArray(b.anyOf) || Array.isArray(b.oneOf))
		) {
			const inner = collectUnion((b.anyOf ?? b.oneOf) as unknown[]);
			objects.push(...inner.objects);
			hasNull = hasNull || inner.hasNull;
		}
	}
	return { objects, hasNull };
}

function mergeObjectUnion(objects: Schema[], hasNull: boolean): Schema {
	const mergedProps: Record<string, Schema> = {};
	const requiredSets: Set<string>[] = [];
	for (const obj of objects) {
		const props = (obj.properties as Record<string, Schema>) ?? {};
		for (const [key, val] of Object.entries(props)) {
			const simplified = simplifyConstrainedSchema(val);
			const existing = mergedProps[key];
			if (
				existing &&
				Array.isArray(existing.enum) &&
				Array.isArray(simplified.enum)
			) {
				// merge discriminator enums (e.g. kind: "a" | "b")
				mergedProps[key] = {
					...simplified,
					enum: Array.from(
						new Set([
							...(existing.enum as unknown[]),
							...(simplified.enum as unknown[]),
						]),
					).sort(),
				};
			} else if (!existing) {
				mergedProps[key] = simplified;
			}
		}
		requiredSets.push(new Set((obj.required as string[]) ?? []));
	}
	const required =
		requiredSets.length > 0
			? [
					...requiredSets.reduce(
						(a, b) => new Set([...a].filter((x) => b.has(x))),
					),
				].sort()
			: [];
	return {
		type: hasNull ? ["object", "null"] : "object",
		properties: mergedProps,
		required,
		additionalProperties: false,
	};
}

export function simplifyConstrainedSchema(input: unknown): Schema {
	if (!isSchema(input)) {
		return input as Schema;
	}

	// Union handling: only collapse when at least one branch is an OBJECT. Scalar
	// unions (string|null etc.) are left intact.
	const unionKey = Array.isArray(input.anyOf)
		? "anyOf"
		: Array.isArray(input.oneOf)
			? "oneOf"
			: null;
	if (unionKey) {
		const branches = input[unionKey] as unknown[];
		const { objects, hasNull } = collectUnion(branches);
		if (objects.length > 0) {
			return mergeObjectUnion(objects, hasNull);
		}
		// scalar / non-object union: recurse into branches but keep the union shape
		return {
			...input,
			[unionKey]: branches.map((b) => simplifyConstrainedSchema(b)),
		};
	}

	const out: Schema = { ...input };

	// const -> single-value enum
	if ("const" in out) {
		out.enum = [out.const];
		delete out.const;
	}

	// tuple-form items -> single item schema
	if (Array.isArray(out.items)) {
		out.items = simplifyConstrainedSchema((out.items as unknown[])[0]);
	} else if (isSchema(out.items)) {
		out.items = simplifyConstrainedSchema(out.items);
	}

	// recurse into properties
	if (isSchema(out.properties)) {
		const props = out.properties as Record<string, unknown>;
		const next: Record<string, Schema> = {};
		for (const [k, v] of Object.entries(props)) {
			next[k] = simplifyConstrainedSchema(v);
		}
		out.properties = next;
	}

	return out;
}
