name = "piano-analyzer-backend"
main = "build/worker.js"
compatibility_date = "2023-05-18"

[build]
command = "cargo build --target wasm32-unknown-unknown --release && wasm-bindgen --out-dir build --target bundler --no-typescript target/wasm32-unknown-unknown/release/piano_analyzer_backend.wasm"

[vars]
WORKERS_RS_VERSION = "0.3.0"

[[r2_buckets]]
binding = "AUDIO_BUCKET"
bucket_name = "piano-audio-storage"
preview_bucket_name = "piano-audio-storage-preview"