# Pseudo-label Pre-training Configuration
# Stage 2: Pre-train on MAESTRO pseudo-labels

data:
  # Annotation paths
  train_path: data/maestro_pseudo_labels_train.jsonl
  val_path: data/maestro_pseudo_labels_val.jsonl
  test_path: null

  # Dimensions (technical only for pseudo-labels)
  dimensions:
    - note_accuracy
    - rhythmic_precision
    - dynamics_control
    - articulation_quality
    - pedaling_technique
    - tone_quality

  # Audio settings
  audio_sample_rate: 24000
  max_audio_length: 240000  # 10 seconds at 24kHz
  max_midi_events: 512

  # DataLoader settings
  batch_size: 8
  num_workers: 4
  pin_memory: true

  # Augmentation (training only)
  augmentation:
    enabled: true
    pitch_shift:
      enabled: true
      probability: 0.3
      min_semitones: -2
      max_semitones: 2
    time_stretch:
      enabled: true
      probability: 0.3
      min_rate: 0.85
      max_rate: 1.15
    add_noise:
      enabled: true
      probability: 0.2
      min_snr_db: 25
      max_snr_db: 40
    room_acoustics:
      enabled: true
      probability: 0.2
      num_room_types: 5
    compress_audio:
      enabled: true
      probability: 0.15
      bitrates: [128, 192, 256, 320]
    gain_variation:
      enabled: true
      probability: 0.3
      min_db: -6
      max_db: 6
    max_transforms: 3  # Apply at most 3 transforms per sample

model:
  # Architecture dimensions
  audio_dim: 768
  midi_dim: 256
  fusion_dim: 1024
  aggregator_dim: 512
  num_dimensions: 6  # Only technical dimensions

  # Encoder settings
  mert_model_name: m-a-p/MERT-v1-95M
  freeze_audio_encoder: false
  gradient_checkpointing: true

  # MIDI encoder
  midi_hidden_size: 256
  midi_num_layers: 6
  midi_num_heads: 4

  # Fusion
  fusion_num_heads: 8
  fusion_dropout: 0.1

  # Aggregator
  lstm_hidden: 256
  lstm_layers: 2
  attention_heads: 4
  aggregator_dropout: 0.2

  # MTL Head
  shared_hidden: 256
  task_hidden: 128
  mtl_dropout: 0.1

training:
  # Training duration
  max_epochs: 20
  precision: 16  # Mixed precision (FP16)

  # Optimization
  optimizer: AdamW
  learning_rate: 1e-5  # Default (not used, see backbone_lr and heads_lr)
  backbone_lr: 1e-5  # Lower LR for pre-trained encoders
  heads_lr: 1e-4  # Higher LR for task heads
  weight_decay: 0.01

  # Learning rate schedule
  scheduler: cosine
  warmup_steps: 500
  min_lr: 1e-6

  # Gradient settings
  gradient_clip_val: 1.0
  accumulate_grad_batches: 4  # Effective batch size = 8 * 4 = 32

  # Validation
  val_check_interval: 1.0  # Check every epoch
  limit_val_batches: 1.0  # Use full val set

callbacks:
  # Model checkpointing
  checkpoint:
    monitor: val_loss
    mode: min
    save_top_k: 3
    save_last: true
    dirpath: checkpoints/pseudo_pretrain
    filename: pseudo-{epoch:02d}-{val_loss:.4f}

  # Early stopping
  early_stopping:
    monitor: val_loss
    mode: min
    patience: 5
    min_delta: 0.001

  # Learning rate monitoring
  lr_monitor:
    logging_interval: step

logging:
  # Logging frequency
  log_every_n_steps: 50

  # WandB (optional)
  use_wandb: false
  wandb_project: piano-eval-mvp
  wandb_entity: null
  wandb_run_name: pseudo-pretrain

  # TensorBoard
  use_tensorboard: true
  tensorboard_logdir: logs/pseudo_pretrain

seed: 42
