from setuptools import setup, find_packages
setup(
    name="piano_feedback",
    version="0.1.0",
    description="A system for automated feedback on classical piano performances",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Classical Piano Performance Feedback Team",
    author_email="team@pianofeedback.example.com",
    license="MIT",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "numpy>=1.21.0",
        "scipy>=1.7.0",
        "pandas>=1.3.0",
        "librosa>=0.8.1",
        "soundfile>=0.10.3",
        "scikit-learn>=1.0.0",
        "torch>=1.9.0",
        "torchaudio>=0.9.0",
        "torchvision>=0.10.0",
        "transformers>=4.12.0",
        "click>=8.0.0",
        "pytest>=6.2.4",
        "pytest-cov>=2.12.1",
        "tqdm>=4.62.0",
        "matplotlib>=3.4.3",
        "seaborn>=0.11.2",
        "jsonschema>=4.0.0"
    ],
    entry_points={
        "console_scripts": [
            "piano-feedback=scripts.run_inference:main",
        ],
    },
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
    ],
)
