"""Utilities for dataset management (manifests, deduplication, probes).

CLI entrypoints:
- python -m src.tools.build_manifest ...
- python -m src.tools.dedup_audio ...
- python -m src.tools.dataset_probe ...
"""
