name = "piano-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2024-01-01"
workers_dev = true

# R2 Storage (PDF files)
[[r2_buckets]]
binding = "PDFS_BUCKET"
bucket_name = "piano-pdfs"

[[r2_buckets]]
binding = "KNOWLEDGE_BUCKET"
bucket_name = "piano-knowledge"

# Workers KV (3-layer cache)
[[kv_namespaces]]
binding = "EMBEDDING_CACHE"
id = "e88f6058dea9404a9c9d2c5e07f06899"

[[kv_namespaces]]
binding = "SEARCH_CACHE"
id = "42d783da9d434366bd5d2ffaba78bbed"

[[kv_namespaces]]
binding = "LLM_CACHE"
id = "bd6541961f194b7d869abbc967f58699"

# Workers AI binding (embeddings, re-ranking)
[ai]
binding = "AI"

# Environment variables
[vars]
GCP_API_URL = "http://localhost:8080"  # Update with your GCP API URL after deployment
ENVIRONMENT = "development"

# Build configuration
[build]
command = "cargo install -q worker-build && worker-build --release"

# Routes (update with your domain after Cloudflare setup)
# routes = [
#   { pattern = "api.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]
