name = "piano-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2024-01-01"
workers_dev = true

# Bindings - zero-latency access to Cloudflare services

# R2 Storage (PDF files)
[[r2_buckets]]
binding = "PDFS_BUCKET"
bucket_name = "piano-pdfs"

[[r2_buckets]]
binding = "KNOWLEDGE_BUCKET"
bucket_name = "piano-knowledge"

# Workers KV (3-layer cache)
[[kv_namespaces]]
binding = "EMBEDDING_CACHE"
id = "TO_BE_CREATED"  # Run: wrangler kv:namespace create "EMBEDDING_CACHE"

[[kv_namespaces]]
binding = "SEARCH_CACHE"
id = "TO_BE_CREATED"  # Run: wrangler kv:namespace create "SEARCH_CACHE"

[[kv_namespaces]]
binding = "LLM_CACHE"
id = "TO_BE_CREATED"  # Run: wrangler kv:namespace create "LLM_CACHE"

# Workers AI binding (embeddings, re-ranking)
[ai]
binding = "AI"

# Environment variables
[vars]
GCP_API_URL = "http://localhost:8080"  # Update with your GCP API URL after deployment
ENVIRONMENT = "development"

# Secrets (set via: wrangler secret put <NAME>)
# - SUPABASE_JWT_SECRET (for JWT validation)
# - GCP_API_TOKEN (optional, for authenticating Worker -> GCP API calls)

# Build configuration
[build]
command = "cargo install -q worker-build && worker-build --release"

[build.upload]
format = "modules"
main = "./build/worker/shim.mjs"

# Routes (update with your domain after Cloudflare setup)
# routes = [
#   { pattern = "api.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]
