use crate::models::PerformanceDimensions;

/// Mock RunPod service that returns realistic dimension scores.
/// In production, this will call the actual RunPod GPU inference endpoint.
pub async fn get_performance_dimensions(performance_id: &str) -> PerformanceDimensions {
    // Generate slightly different scores based on the performance ID
    // to make each analysis feel unique
    let seed = performance_id.bytes().fold(0u32, |acc, b| acc.wrapping_add(b as u32));
    let variation = |base: f64, offset: u32| -> f64 {
        let v = ((seed.wrapping_add(offset) % 100) as f64) / 500.0 - 0.1;
        (base + v).clamp(0.5, 0.98)
    };

    match performance_id {
        "horowitz-chopin-ballade-1" => PerformanceDimensions {
            timing: 0.92,
            articulation_length: 0.88,
            articulation_touch: 0.94,
            pedal_amount: 0.85,
            pedal_clarity: 0.82,
            timbre_variety: 0.95,
            timbre_depth: 0.93,
            timbre_brightness: 0.88,
            timbre_loudness: 0.90,
            dynamics_range: 0.96,
            tempo: 0.87,
            space: 0.84,
            balance: 0.91,
            drama: 0.97,
            mood_valence: 0.72,
            mood_energy: 0.94,
            mood_imagination: 0.93,
            interpretation_sophistication: 0.95,
            interpretation_overall: 0.94,
        },
        "argerich-prokofiev-toccata" => PerformanceDimensions {
            timing: 0.94,
            articulation_length: 0.91,
            articulation_touch: 0.89,
            pedal_amount: 0.72,
            pedal_clarity: 0.88,
            timbre_variety: 0.86,
            timbre_depth: 0.84,
            timbre_brightness: 0.93,
            timbre_loudness: 0.95,
            dynamics_range: 0.92,
            tempo: 0.96,
            space: 0.78,
            balance: 0.87,
            drama: 0.94,
            mood_valence: 0.65,
            mood_energy: 0.98,
            mood_imagination: 0.88,
            interpretation_sophistication: 0.91,
            interpretation_overall: 0.92,
        },
        "gould-bach-goldberg-aria" => PerformanceDimensions {
            timing: 0.96,
            articulation_length: 0.94,
            articulation_touch: 0.92,
            pedal_amount: 0.55,
            pedal_clarity: 0.95,
            timbre_variety: 0.78,
            timbre_depth: 0.88,
            timbre_brightness: 0.82,
            timbre_loudness: 0.68,
            dynamics_range: 0.72,
            tempo: 0.65,
            space: 0.94,
            balance: 0.96,
            drama: 0.62,
            mood_valence: 0.85,
            mood_energy: 0.58,
            mood_imagination: 0.92,
            interpretation_sophistication: 0.97,
            interpretation_overall: 0.94,
        },
        "zimerman-chopin-ballade-4" => PerformanceDimensions {
            timing: 0.95,
            articulation_length: 0.93,
            articulation_touch: 0.96,
            pedal_amount: 0.88,
            pedal_clarity: 0.91,
            timbre_variety: 0.92,
            timbre_depth: 0.94,
            timbre_brightness: 0.86,
            timbre_loudness: 0.82,
            dynamics_range: 0.93,
            tempo: 0.84,
            space: 0.90,
            balance: 0.95,
            drama: 0.88,
            mood_valence: 0.78,
            mood_energy: 0.82,
            mood_imagination: 0.95,
            interpretation_sophistication: 0.96,
            interpretation_overall: 0.95,
        },
        "kissin-rachmaninoff-prelude" => PerformanceDimensions {
            timing: 0.91,
            articulation_length: 0.86,
            articulation_touch: 0.88,
            pedal_amount: 0.92,
            pedal_clarity: 0.78,
            timbre_variety: 0.89,
            timbre_depth: 0.91,
            timbre_brightness: 0.87,
            timbre_loudness: 0.93,
            dynamics_range: 0.95,
            tempo: 0.92,
            space: 0.82,
            balance: 0.88,
            drama: 0.93,
            mood_valence: 0.68,
            mood_energy: 0.96,
            mood_imagination: 0.86,
            interpretation_sophistication: 0.88,
            interpretation_overall: 0.90,
        },
        "pollini-beethoven-appassionata" => PerformanceDimensions {
            timing: 0.93,
            articulation_length: 0.90,
            articulation_touch: 0.87,
            pedal_amount: 0.82,
            pedal_clarity: 0.86,
            timbre_variety: 0.88,
            timbre_depth: 0.92,
            timbre_brightness: 0.84,
            timbre_loudness: 0.91,
            dynamics_range: 0.94,
            tempo: 0.89,
            space: 0.85,
            balance: 0.93,
            drama: 0.95,
            mood_valence: 0.62,
            mood_energy: 0.94,
            mood_imagination: 0.87,
            interpretation_sophistication: 0.94,
            interpretation_overall: 0.93,
        },
        // Default fallback with generated values
        _ => PerformanceDimensions {
            timing: variation(0.85, 1),
            articulation_length: variation(0.82, 2),
            articulation_touch: variation(0.84, 3),
            pedal_amount: variation(0.78, 4),
            pedal_clarity: variation(0.80, 5),
            timbre_variety: variation(0.83, 6),
            timbre_depth: variation(0.85, 7),
            timbre_brightness: variation(0.81, 8),
            timbre_loudness: variation(0.82, 9),
            dynamics_range: variation(0.86, 10),
            tempo: variation(0.84, 11),
            space: variation(0.79, 12),
            balance: variation(0.85, 13),
            drama: variation(0.83, 14),
            mood_valence: variation(0.72, 15),
            mood_energy: variation(0.84, 16),
            mood_imagination: variation(0.81, 17),
            interpretation_sophistication: variation(0.84, 18),
            interpretation_overall: variation(0.85, 19),
        },
    }
}
