import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { parseYaml } from "../src/harness/skills/validator";

export interface SkillEntry {
	name: string;
	description: string;
}

export interface SkillCatalog {
	atoms: SkillEntry[];
	molecules: SkillEntry[];
	compounds: SkillEntry[];
}

function extractFrontmatter(md: string): Record<string, unknown> {
	const match = md.match(/^---\n([\s\S]+?)\n---/);
	if (!match) return {};
	const parsed = parseYaml(match[1]);
	return typeof parsed === "object" && parsed !== null
		? (parsed as Record<string, unknown>)
		: {};
}

function readTier(dir: string): SkillEntry[] {
	const entries: SkillEntry[] = [];
	for (const file of readdirSync(dir)) {
		if (!file.endsWith(".md") || file === "README.md") continue;
		const md = readFileSync(join(dir, file), "utf-8");
		const fm = extractFrontmatter(md);
		const name = typeof fm["name"] === "string" ? fm["name"] : null;
		const description =
			typeof fm["description"] === "string" ? fm["description"] : null;
		if (!name || !description) {
			throw new Error(
				`catalog-codegen: missing 'name' or 'description' in ${join(dir, file)}`,
			);
		}
		entries.push({ name, description });
	}
	entries.sort((a, b) => a.name.localeCompare(b.name));
	return entries;
}

export function parseCatalog(skillsDir: string): SkillCatalog {
	return {
		atoms: readTier(join(skillsDir, "atoms")),
		molecules: readTier(join(skillsDir, "molecules")),
		compounds: readTier(join(skillsDir, "compounds")),
	};
}

export function emitCatalog(skillsDir: string, outputPath: string): void {
	const cat = parseCatalog(skillsDir);
	const body = JSON.stringify(cat, null, 2);
	const content =
		"// AUTO-GENERATED by scripts/catalog-codegen.ts — do not edit.\n" +
		"// Run `bun scripts/catalog-codegen.ts` to regenerate.\n\n" +
		"import type { SkillCatalog } from '../../../../scripts/catalog-codegen';\n\n" +
		`export const catalog: SkillCatalog = ${body} as const;\n`;
	mkdirSync(dirname(outputPath), { recursive: true });
	writeFileSync(outputPath, content);
}

if (import.meta.main) {
	const skillsDir =
		process.env["CRESCENDAI_SKILLS_DIR"] ??
		join(__dirname, "../../../docs/harness/skills");
	const outPath = join(
		__dirname,
		"../src/harness/skills/__catalog__/index.gen.ts",
	);
	emitCatalog(skillsDir, outPath);
	console.log(`Wrote ${outPath}`);
}
